# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FaceUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_face(object):
    def setupUi(self, Form_face):
        Form_face.setObjectName("Form_face")
        Form_face.resize(1064, 729)
        Form_face.setStyleSheet("color:#a4a5a8;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form_face)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_top = QtWidgets.QWidget(Form_face)
        self.widget_top.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_top.setObjectName("widget_top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_top)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_face_back_2 = QtWidgets.QPushButton(self.widget_top)
        self.pushButton_face_back_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_face_back_2.setStyleSheet("")
        self.pushButton_face_back_2.setFlat(True)
        self.pushButton_face_back_2.setObjectName("pushButton_face_back_2")
        self.horizontalLayout_2.addWidget(self.pushButton_face_back_2)
        self.label = QtWidgets.QLabel(self.widget_top)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.pushButton_second_back = QtWidgets.QPushButton(self.widget_top)
        self.pushButton_second_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_second_back.setText("")
        self.pushButton_second_back.setFlat(True)
        self.pushButton_second_back.setObjectName("pushButton_second_back")
        self.horizontalLayout_2.addWidget(self.pushButton_second_back)
        self.label_3 = QtWidgets.QLabel(self.widget_top)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.pushButton = QtWidgets.QPushButton(self.widget_top)
        self.pushButton.setText("")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(728, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_top)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_top)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.verticalLayout.addWidget(self.widget_top)
        self.widget_bottom = QtWidgets.QWidget(Form_face)
        self.widget_bottom.setObjectName("widget_bottom")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_bottom)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_main = QtWidgets.QGridLayout()
        self.gridLayout_main.setObjectName("gridLayout_main")
        self.gridLayout.addLayout(self.gridLayout_main, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_bottom)

        self.retranslateUi(Form_face)
        self.pushButton_face_back_2.clicked.connect(Form_face.goFaceMain)
        self.pushButton_5.clicked.connect(Form_face.goFaceTaskPage)
        self.pushButton_4.clicked.connect(Form_face.goLibraryManagementPage)
        QtCore.QMetaObject.connectSlotsByName(Form_face)

    def retranslateUi(self, Form_face):
        _translate = QtCore.QCoreApplication.translate
        Form_face.setWindowTitle(_translate("Form_face", "Form"))
        self.pushButton_face_back_2.setText(_translate("Form_face", "face_recognize"))
        self.label.setText(_translate("Form_face", ">"))
        self.label_3.setText(_translate("Form_face", ">"))
        self.pushButton_5.setText(_translate("Form_face", "new_task"))
        self.pushButton_5.setProperty("class", _translate("Form_face", "primary"))
        self.pushButton_5.setProperty("sizeBtn", _translate("Form_face", "medium"))
        self.pushButton_4.setText(_translate("Form_face", "face_manage"))
        self.pushButton_4.setProperty("class", _translate("Form_face", "primary"))
        self.pushButton_4.setProperty("sizeBtn", _translate("Form_face", "medium"))
