# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FaceUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1064, 729)
        Form.setStyleSheet("color:#a4a5a8;")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.widget_top = QtWidgets.QWidget(Form)
        self.widget_top.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_top.setObjectName("widget_top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_top)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_face_back = QtWidgets.QPushButton(self.widget_top)
        self.pushButton_face_back.setStyleSheet("")
        self.pushButton_face_back.setFlat(True)
        self.pushButton_face_back.setObjectName("pushButton_face_back")
        self.horizontalLayout.addWidget(self.pushButton_face_back)
        self.line = QtWidgets.QFrame(self.widget_top)
        self.line.setMaximumSize(QtCore.QSize(16777215, 20))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.label = QtWidgets.QLabel(self.widget_top)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(729, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_top)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_top)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.gridLayout.addWidget(self.widget_top, 0, 0, 1, 1)
        self.widget_bottom = QtWidgets.QWidget(Form)
        self.widget_bottom.setObjectName("widget_bottom")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_bottom)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_main = QtWidgets.QGridLayout()
        self.gridLayout_main.setObjectName("gridLayout_main")
        self.gridLayout_4.addLayout(self.gridLayout_main, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_bottom, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.pushButton_2.clicked.connect(Form.goFaceTaskPage)
        self.pushButton_3.clicked.connect(Form.goLibraryManagementPage)
        self.pushButton_face_back.clicked.connect(Form.goFaceMain)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_face_back.setText(_translate("Form", "人脸识别"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.pushButton_2.setText(_translate("Form", "新建任务"))
        self.pushButton_2.setProperty("class", _translate("Form", "primary"))
        self.pushButton_2.setProperty("sizeBtn", _translate("Form", "medium"))
        self.pushButton_3.setText(_translate("Form", "人脸管理"))
        self.pushButton_3.setProperty("class", _translate("Form", "primary"))
        self.pushButton_3.setProperty("sizeBtn", _translate("Form", "medium"))
