# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FaceUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1064, 729)
        Form.setStyleSheet("color:#a4a5a8;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_top = QtWidgets.QWidget(Form)
        self.widget_top.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_top.setObjectName("widget_top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_top)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_face_back_2 = QtWidgets.QPushButton(self.widget_top)
        self.pushButton_face_back_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_face_back_2.setStyleSheet("")
        self.pushButton_face_back_2.setFlat(True)
        self.pushButton_face_back_2.setObjectName("pushButton_face_back_2")
        self.horizontalLayout_2.addWidget(self.pushButton_face_back_2)
        self.line = QtWidgets.QFrame(self.widget_top)
        self.line.setMaximumSize(QtCore.QSize(16777215, 15))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.pushButton_second_back = QtWidgets.QPushButton(self.widget_top)
        self.pushButton_second_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_second_back.setFlat(True)
        self.pushButton_second_back.setObjectName("pushButton_second_back")
        self.horizontalLayout_2.addWidget(self.pushButton_second_back)
        self.line_2 = QtWidgets.QFrame(self.widget_top)
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 15))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.label_2 = QtWidgets.QLabel(self.widget_top)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(728, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_top)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_top)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.verticalLayout.addWidget(self.widget_top)
        self.widget_bottom = QtWidgets.QWidget(Form)
        self.widget_bottom.setObjectName("widget_bottom")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_bottom)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_main = QtWidgets.QGridLayout()
        self.gridLayout_main.setObjectName("gridLayout_main")
        self.gridLayout.addLayout(self.gridLayout_main, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_bottom)

        self.retranslateUi(Form)
        self.pushButton_face_back_2.clicked.connect(Form.goFaceMain)
        self.pushButton_5.clicked.connect(Form.goFaceTaskPage)
        self.pushButton_4.clicked.connect(Form.goLibraryManagementPage)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_face_back_2.setText(_translate("Form", "人脸识别"))
        self.pushButton_second_back.setText(_translate("Form", "PushButton"))
        self.label_2.setText(_translate("Form", "任务列表"))
        self.pushButton_5.setText(_translate("Form", "新建任务"))
        self.pushButton_5.setProperty("class", _translate("Form", "primary"))
        self.pushButton_5.setProperty("sizeBtn", _translate("Form", "medium"))
        self.pushButton_4.setText(_translate("Form", "人脸管理"))
        self.pushButton_4.setProperty("class", _translate("Form", "primary"))
        self.pushButton_4.setProperty("sizeBtn", _translate("Form", "medium"))
