# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomeLayoutUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_home(object):
    def setupUi(self, Form_home):
        Form_home.setObjectName("Form_home")
        Form_home.resize(1175, 775)
        self.gridLayout = QtWidgets.QGridLayout(Form_home)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_top = QtWidgets.QWidget(Form_home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_top.sizePolicy().hasHeightForWidth())
        self.widget_top.setSizePolicy(sizePolicy)
        self.widget_top.setMaximumSize(QtCore.QSize(16777215, 70))
        self.widget_top.setObjectName("widget_top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_top)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_top = QtWidgets.QHBoxLayout()
        self.horizontalLayout_top.setSpacing(0)
        self.horizontalLayout_top.setObjectName("horizontalLayout_top")
        self.horizontalLayout_2.addLayout(self.horizontalLayout_top)
        self.verticalLayout.addWidget(self.widget_top)
        self.widget = QtWidgets.QWidget(Form_home)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_main = QtWidgets.QGridLayout()
        self.gridLayout_main.setObjectName("gridLayout_main")
        self.gridLayout_3.addLayout(self.gridLayout_main, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.widget_bottom = QtWidgets.QWidget(Form_home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_bottom.sizePolicy().hasHeightForWidth())
        self.widget_bottom.setSizePolicy(sizePolicy)
        self.widget_bottom.setMaximumSize(QtCore.QSize(16777215, 20))
        self.widget_bottom.setObjectName("widget_bottom")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_bottom)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.widget_bottom)
        self.label.setAcceptDrops(True)
        self.label.setLineWidth(0)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout.addWidget(self.widget_bottom)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form_home)
        QtCore.QMetaObject.connectSlotsByName(Form_home)

    def retranslateUi(self, Form_home):
        _translate = QtCore.QCoreApplication.translate
        Form_home.setWindowTitle(_translate("Form_home", "Form"))
        self.label.setText(_translate("Form_home", "© 2020 Aupera Technologies Inc."))
