# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LiveUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_live(object):
    def setupUi(self, Form_live):
        Form_live.setObjectName("Form_live")
        Form_live.resize(998, 724)
        Form_live.setStyleSheet("color:#a4a5a8;")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form_live)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_left = QtWidgets.QWidget(Form_live)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_left.sizePolicy().hasHeightForWidth())
        self.widget_left.setSizePolicy(sizePolicy)
        self.widget_left.setMinimumSize(QtCore.QSize(275, 0))
        self.widget_left.setMaximumSize(QtCore.QSize(275, 16777215))
        self.widget_left.setStyleSheet("#widget_left{\n"
"    background-color:#191d2d;\n"
"    border:1px solid #2e3557;\n"
"}\n"
"")
        self.widget_left.setObjectName("widget_left")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_left)
        self.verticalLayout.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_live_tool = QtWidgets.QWidget(self.widget_left)
        self.widget_live_tool.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_live_tool.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_live_tool.setObjectName("widget_live_tool")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_live_tool)
        self.horizontalLayout_3.setContentsMargins(10, 0, 7, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_onvif = QtWidgets.QPushButton(self.widget_live_tool)
        self.pushButton_onvif.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_onvif.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_onvif.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_onvif.setText("")
        self.pushButton_onvif.setObjectName("pushButton_onvif")
        self.horizontalLayout_3.addWidget(self.pushButton_onvif)
        self.pushButton_add_camera = QtWidgets.QPushButton(self.widget_live_tool)
        self.pushButton_add_camera.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_add_camera.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_add_camera.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_add_camera.setToolTip("")
        self.pushButton_add_camera.setText("")
        self.pushButton_add_camera.setFlat(False)
        self.pushButton_add_camera.setObjectName("pushButton_add_camera")
        self.horizontalLayout_3.addWidget(self.pushButton_add_camera)
        self.verticalLayout.addWidget(self.widget_live_tool)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_title = QtWidgets.QLabel(self.widget_left)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout.addWidget(self.label_title)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listWidget = QtWidgets.QListWidget(self.widget_left)
        self.listWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.listWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listWidget.setStyleSheet("background:transparent;\n"
"border:none;")
        self.listWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.listWidget.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout_2.addWidget(self.widget_left)
        self.widget_video_show = QtWidgets.QWidget(Form_live)
        self.widget_video_show.setStyleSheet("")
        self.widget_video_show.setObjectName("widget_video_show")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_video_show)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_video = QtWidgets.QHBoxLayout()
        self.horizontalLayout_video.setSpacing(0)
        self.horizontalLayout_video.setObjectName("horizontalLayout_video")
        self.gridLayout_3.addLayout(self.horizontalLayout_video, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.widget_video_show)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Form_live)
        self.pushButton_add_camera.clicked.connect(Form_live.addCameraDialogShow)
        self.listWidget.itemClicked['QListWidgetItem*'].connect(Form_live.handleCameraChanged)
        QtCore.QMetaObject.connectSlotsByName(Form_live)

    def retranslateUi(self, Form_live):
        _translate = QtCore.QCoreApplication.translate
        Form_live.setWindowTitle(_translate("Form_live", "Form"))
        self.label_title.setText(_translate("Form_live", "Camera List"))
        self.label_title.setProperty("class", _translate("Form_live", "list_title"))
        self.listWidget.setSortingEnabled(True)
