# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_login(object):
    def setupUi(self, Form_login):
        Form_login.setObjectName("Form_login")
        Form_login.resize(729, 477)
        self.gridLayout = QtWidgets.QGridLayout(Form_login)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form_login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 60))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(60, 60, 60, 60)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label_username = QtWidgets.QLabel(Form_login)
        self.label_username.setObjectName("label_username")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_username)
        self.lineEdit_username = QtWidgets.QLineEdit(Form_login)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_username)
        self.label_password = QtWidgets.QLabel(Form_login)
        self.label_password.setObjectName("label_password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(Form_login)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_password)
        self.login_btn = QtWidgets.QPushButton(Form_login)
        self.login_btn.setObjectName("login_btn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.login_btn)
        self.label_login_title = QtWidgets.QLabel(Form_login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_login_title.sizePolicy().hasHeightForWidth())
        self.label_login_title.setSizePolicy(sizePolicy)
        self.label_login_title.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_login_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_login_title.setObjectName("label_login_title")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_login_title)
        self.verticalLayout.addLayout(self.formLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form_login)
        QtCore.QMetaObject.connectSlotsByName(Form_login)

    def retranslateUi(self, Form_login):
        _translate = QtCore.QCoreApplication.translate
        Form_login.setWindowTitle(_translate("Form_login", "Form"))
        self.label_username.setText(_translate("Form_login", "用户名"))
        self.lineEdit_username.setText(_translate("Form_login", "admin"))
        self.lineEdit_username.setPlaceholderText(_translate("Form_login", "请输入用户名"))
        self.label_password.setText(_translate("Form_login", "密码"))
        self.lineEdit_password.setText(_translate("Form_login", "123456"))
        self.lineEdit_password.setPlaceholderText(_translate("Form_login", "请输入密码"))
        self.login_btn.setText(_translate("Form_login", "登 录"))
        self.label_login_title.setText(_translate("Form_login", "登 录"))
