# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewFaceUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 400)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(110, 360, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(61, 51, 371, 241))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label.sizePolicy().hasHeightForWidth())
        self.Label.setSizePolicy(sizePolicy)
        self.Label.setObjectName("Label")
        self.gridLayout.addWidget(self.Label, 3, 0, 1, 1)
        self.label_image = QtWidgets.QLabel(self.widget)
        self.label_image.setMinimumSize(QtCore.QSize(50, 50))
        self.label_image.setText("")
        self.label_image.setPixmap(QtGui.QPixmap(":/face/static/images/faceIcon.png"))
        self.label_image.setObjectName("label_image")
        self.gridLayout.addWidget(self.label_image, 4, 1, 1, 1)
        self.lineEdit_name = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout.addWidget(self.lineEdit_name, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_age = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_age.setObjectName("lineEdit_age")
        self.gridLayout.addWidget(self.lineEdit_age, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_upload = QtWidgets.QPushButton(self.widget)
        self.pushButton_upload.setObjectName("pushButton_upload")
        self.gridLayout.addWidget(self.pushButton_upload, 3, 1, 1, 1)
        self.lineEdit_sex = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_sex.setObjectName("lineEdit_sex")
        self.gridLayout.addWidget(self.lineEdit_sex, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_tip = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_tip.sizePolicy().hasHeightForWidth())
        self.label_tip.setSizePolicy(sizePolicy)
        self.label_tip.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_tip.setObjectName("label_tip")
        self.gridLayout.addWidget(self.label_tip, 5, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 3)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.pushButton_upload.clicked.connect(Dialog.openImage)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "添加单个人脸"))
        self.Label.setText(_translate("Dialog", "头像"))
        self.label_2.setText(_translate("Dialog", "性别"))
        self.label.setText(_translate("Dialog", "名字"))
        self.pushButton_upload.setText(_translate("Dialog", "上传头像"))
        self.label_3.setText(_translate("Dialog", "年龄"))
        self.label_tip.setText(_translate("Dialog", "请上传图片"))
